### ISSUE TITLE
Allow selection for FCM testing port 5236

### ISSUE THREAD

**Issue by kenshin171** [guness/node-xcs#10]
Is it possible to add an argument to Sender object to specify the port 5236 for testing and development purposes instead of using port 5235 which should be only used for production.

Something like 

```
// Production
fcm-xmpp.googleapis.com:5235

// Testing
fcm-xmpp.googleapis.com:5236

var xcs = new Sender(<server id>, <server key>, <boolean isProduction>);
```

**Comment by guness** [comment]
ok, it is in my TODO now. next version will have it surely.

**Comment by kenshin171** [comment]
Awesome! Many thanks

**Comment by RDLemos** [comment]
Hi, I was about to ask about the same enhancement:
Add an attribute to select Production (fcm-xmpp.googleapis.com:5235) or Testing (fcm-xmpp.googleapis.com:5236) connections...

Do you have already a planned date for the next version release?

**Comment by RDLemos** [comment]
Great, I see that the patch to support the Dev Server has been approved (thanks). Do you plan to release the new version (0.1.5) soon?

**Comment by guness** [comment]
published
