### ISSUE TITLE
No option to set XMPP connection to reconnect

### ISSUE THREAD

**Issue by RDLemos** [guness/node-xcs#15]
Hello,
I believe that there is one issue with the current implementation, related to the possibility to reconnect to the FCM server in case of lost of connection.
The xmpp-node library has an option to pass a parameter { reconnect: true}  to attempt to reconnect the WebSocket, in case the connection is lost. This is very important for the reliability of the Push Notifications, in the case your server recover from a network loss.
The simple solution would be to add this to the parameter passed to Sender(), but I think the best solution, to be as generic as possible, is to change the Sender to accept a configuration object, where you can set the current values, plus some extra values, as for example the reconnect on the xmpp.Client.

**Comment by RDLemos** [comment]
I have just send a Pull Request to add the reconnect option to the default setting on the client

**Comment by guness** [comment]
okay, merged. do you need a release soon?

**Comment by RDLemos** [comment]
Thanks @guness ! If possible, yes. I would like to update the npm with the new version and release the new version to our server by the end of this week.

**Comment by RDLemos** [comment]
@guness : Do you think you would be able to release it before Monday? I would like to update my server with the new version.

**Comment by guness** [comment]
published
