### ISSUE TITLE
Please update dependencies (node-xmpp-client), due to deprecation and vulnerabilities

### ISSUE THREAD

**Issue by ZissisT** [guness/node-xcs#23]
Hello,

This module depends on node-xmpp-client@3.2.0 which is deprecated. Further more, node-xmpp-client depends on request module which has memory leak issue in versions < 2.85.0
(https://github.com/request/request/issues/2938 )

This means that until direct dependencies of this module are updated, this module has a reported memory leak.

Thank you

**Comment by guness** [comment]
should be good now, please try new version and raise if you see problem.
