### ISSUE TITLE
Not receiving receipts

### ISSUE THREAD

**Issue by mathew-kurian** [guness/node-xcs#4]
Can you please confirm the library correctly receives receipts?

**Comment by guness** [comment]
[The last note](https://github.com/guness/node-xcs#notes-on-xcs) says google is not reliable on this matter. Did not test for so long. Are there any improvements?

**Comment by behrad** [comment]
> Can you please confirm the library correctly receives receipts?

No it dosen't if you are setting the boolean true, and that's cause of this line:
https://github.com/guness/node-xcs/blob/master/google/Sender.js#L206
which is ignoring `true` values

@guness Will this be fixed any soon?

**Comment by guness** [comment]
lemme check tonight (10.35AM here right now). I am not available for now.
