### ISSUE TITLE
Consider updating docs to use senderId rather than projectId

### ISSUE THREAD

**Issue by javamonn** [guness/node-xcs#5]
I think it's worth considering updating at least the README to use `senderId` rather than `projectId`. I for one ran into an initial configuration issue by attempting to create a new sender with my GCP project ID instead of the GCM sender ID - didn't notice the discrepancy until I took a look at the GCM reference docs. Would you accept a quick PR for this?

**Comment by guness** [comment]
Seems well, will do on next commit.

**Comment by guness** [comment]
this commit fixes the issue:  https://github.com/guness/node-xcs/commit/9f9e1c478594787d49505bec1e79fab608cd8bf0
